name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
    - name: install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Prepare AppImage
      run: |
        set -x
        version=$(grep -o "SmartSynchronize:.*" README.md | cut -d ' ' -f2)
        echo "SmartSynchronize version: $version"
        version_dl=${version//./_} # Change . to _ in version
        version_dl=$(echo "$version_dl" | cut -d '_' -f1-3) # Remove last _ and numuber in version

        TarName="smartsynchronize-linux-${version_dl}.tar.gz"
        wget -q -c "https://www.syntevo.com/downloads/smartsynchronize/${TarName}"
        tar xf "${TarName}"

        mkdir -p AppDir/usr/
        cp -r smartsynchronize/* AppDir/usr/
        cd AppDir/
        ln -s usr/bin/smartsynchronize.svg SmartSynchronize.svg

        echo '[Desktop Entry]
        Name=SmartSynchronize
        Keywords=git;
        Comment=Git-Client
        Type=Application
        Categories=Development;RevisionControl;
        Terminal=false
        StartupWMClass=SmartSynchronize
        Exec=smartsynchronize.sh %u
        MimeType=x-scheme-handler/git;x-scheme-handler/smartsynchronize;
        Icon=SmartSynchronize' > smartsynchronize.desktop

        echo '#!/bin/bash
        export APPDIR="${APPDIR:-"$(dirname "$(realpath "$0")")"}"
        bash ${APPDIR}/usr/bin/smartsynchronize.sh $@' > AppRun
        chmod +x AppRun
        pwd; ls -lah

        cd ../
        cp README.md AppDir/

    - name: Get appimagetool
      run: |
        #wget -q -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"
        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Built the AppImage
      run: |
        set -x
        version=$(grep -o "SmartSynchronize:.*" README.md | cut -d ' ' -f2)
        echo "SmartSynchronize version: $version"

        ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage AppDir/

        fileName=$(ls SmartSynchronize*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "SmartSynchronize*.AppImage; SmartSynchronize*.zsync; SmartSynchronize*.md5"
          #overwrite: true
          verbose: true
          draft: false
          default_release_name: "SmartSynchronize V in AppImage"
